metadata_directory: /Users/gardness/Coding/mhs/mhs/test_metadata_json

#solr_url: http://:8983/solr
solr_url: http://192.168.0.105:8983/solr/
solr_collection: mhs_photos

batch_size: 50   # documents per POST request
workers: 4       # parallel upload threads
