#Written by CorePropertiesLocator
#Sat May 23 16:08:36 UTC 2026
collection=mhs_photos
collection.configName=_default
coreNodeName=core_node2
name=mhs_photos_shard1_replica_n1
replicaType=NRT
shard=shard1
